version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: redis-express-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
